version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  asynqmon:
    image: hibiken/asynqmon:latest
    ports:
      - '8080:8080'
    command: ./asynqmon --redis-addr=redis:6379 --redis-db=0 ==redis-password=""