version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  asynqmon:
    image: hibiken/asynqmon:latest
    ports:
      - '8080:8080'
    docker run --rm \
    -p 8080:8080
    hibiken/asynqmon --redis-addr=redis:6379